language: node_js
node_js:
  - lts/*
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: GTAvyO50Y56BFnP5kgrYo7JdT8OxFClio8fczk+Px1lxOKtFcKniXoResxMe/Ssl7LSiYlrSTbNk/M7cHNh1tBxkeSEYYOSvYbydu/L+0wQYSWm6XbHUn4fyc94ywb0r+fQj2XvlvQgGErWNBHXXXpyj55Q6n4qIIfDaVQdzLr0bTQX2c5c+hjkckTOMIkGBwzUEo3+C08JR8dm79rSxEQoQyB/jMyl5YbMPf3UWntzexqe7kQHjkglkCM8bobqGpTd2fmhKFHqkHJVfQ5p0tzfIMChxWNj5EzctKIddskqjR3eemwyyDluBF7fe3GMKWsjXvRsGewRLg68S87TjU6SpiTHnttsIo0GiarXri8lK2pqFTe5lwyib1LDrly5Vuv99TTFClDklQFLcsv+E9ju6pe/5is4lZmmmBk8s0ojTElDUe+Y44KBKdOJS0Q3jW/8Kw7qMepzjYTVGlemPZGdWoyDfJ2d04LhdVseRyU9P57FUKNKKuVHLCO+hp2lCA/PExV61uA7E/yeqEsncE098+owgbVATMV1ZqY+q+IqO6aYz6J9csRuUq9VrQyhmnjPiIiGwxjB0XwI3+lNum7DXsAv0rhUWdUyHO1ZyVs/F4fnOvUUYjnsXHNHrhyOutRmqyrxUuk9qEs/ObmhHWdKODkeUgFJqWd+avovirc8=
script:
  - sonar-scanner
deploy:
  provider: npm
  api_token:
    secure: s4D98zUZ2cuGc4+bNDB6OOvcGc4guMQ+SVsVLSS3Deq0aKX/QQVamP/IS9G5DbxNxxDrWplHhuLTzcsLYBgQ0vmn2vqLLxJOcyYX93+7mnQvYxLwilkVMfVEtmqV1Nf2bKNlyZk+LnjPNp8+yyWdUaLDzt0GG0YwLaoLZPUxdjV1i532MItFmlwBdEOl3olxpJ9qEh5YxL9sJ92vFbmCg3f65/bv8n1I70AVKiwXYyXjhSXz61w8j6rDAWfQ24jq5m+qvDrpEIuUENZbD45XBX09g6Kmu7CuPvwfiO5z6TBxWajIEVXZcUV+U9y58RKwcuWFagNSr5j5oXZhUqXdEJVFuHIpbrXUthn0YdST/0nsidXwMuzrIcperI7+mCUi/gxZ4tKEODUbq176niDOVnBc5aV02sHPY3yKn6clo4w7l1ng3GwzGFH7qMC6EoTXaUPoALlE09OXaQBGNvSy2rJgKP//GNnqj8N3YzStUje5Car5MJaI3rKo0pNyLT0rMm+hXdubEKmiYFpp6QziXXVXICu5MX9hJAjEbPkyw7pDGeGi3M2eAE2I3QAR8JS/cuB/qo76KnJbHcrvULTi3KrCgyA55PhEENrt09s0u2z/stp+arAv3f3GI/5ECZ/JkL0hmJMRHSXczXfF5MMw7e3fvC0Rk5xcXs9Ie7J1ylA=
  on:
    tags: true
  edge: true