language: node_js
node_js:
  - lts/*
branches:
  only:
    - master  
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/    
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: RTMhhr37hbk+n4TEmTdheFA9QYcFS9zUiZJbilVQZ2ttwoohJdsT3Zd40cV0ipPJwFcgjcJ/+w8tVm6G8Uxi3BfAP2VZxHgSuqI2FKyw28s9Dk2pY+IpmYmF4eAtyodo7tebOODuKzpytaWivIua0JsG7Efy/h5j5xGUT4AUcH7sWheGNC3tuRzjbSdGR43SQ2nR6ljok+xAF8Gek9qKMe9SRn4UPbrpupOvbIQK0zs8Gv6io6p7LrSYShQNQeCpTSZ5ZChFT1g9EjiwVuw4V5+FtXR/Gnm46rfpWQA0tID2PCAeTtME3gKkcJuqVXdUg6t8IRpmh+atFdURRhqbIIfYkyOEVhG1ZTs08bwPuUtkay4ADyYlwebT42ECNQgCmp/Gm/X0/nPsR1PR8oJWszn0UNLHldE7jAwG7MnEXDZSdxWBgXyRfl05TIFmzgWgjSyfQWwmaa5M1+8+krb60ZHoQrDjGxXFEsPE1oTs8HMEf2YZ8gP78ZpZF723mu1DJAlsp9p0OKYTkjlTfJzc3eDRMzFquV37XImDcmgAK4VrRQ2sB2TS03JPaVEWwNsLE/gpgXsuhb5icgjPMmrOlVDARk458RnbNmD0AnzGsG6rdhlyE9hWRp1y3vQ0r+KkWfwoU6uZ/yzrWE4R8NlbcgyEnVqmRMVR1KWMrZYh4+w=
script:
  - npm run lint
  - npm test
  - npm run build
  - sonar-scanner
deploy:
  provider: npm
  api_token:
    secure: s4D98zUZ2cuGc4+bNDB6OOvcGc4guMQ+SVsVLSS3Deq0aKX/QQVamP/IS9G5DbxNxxDrWplHhuLTzcsLYBgQ0vmn2vqLLxJOcyYX93+7mnQvYxLwilkVMfVEtmqV1Nf2bKNlyZk+LnjPNp8+yyWdUaLDzt0GG0YwLaoLZPUxdjV1i532MItFmlwBdEOl3olxpJ9qEh5YxL9sJ92vFbmCg3f65/bv8n1I70AVKiwXYyXjhSXz61w8j6rDAWfQ24jq5m+qvDrpEIuUENZbD45XBX09g6Kmu7CuPvwfiO5z6TBxWajIEVXZcUV+U9y58RKwcuWFagNSr5j5oXZhUqXdEJVFuHIpbrXUthn0YdST/0nsidXwMuzrIcperI7+mCUi/gxZ4tKEODUbq176niDOVnBc5aV02sHPY3yKn6clo4w7l1ng3GwzGFH7qMC6EoTXaUPoALlE09OXaQBGNvSy2rJgKP//GNnqj8N3YzStUje5Car5MJaI3rKo0pNyLT0rMm+hXdubEKmiYFpp6QziXXVXICu5MX9hJAjEbPkyw7pDGeGi3M2eAE2I3QAR8JS/cuB/qo76KnJbHcrvULTi3KrCgyA55PhEENrt09s0u2z/stp+arAv3f3GI/5ECZ/JkL0hmJMRHSXczXfF5MMw7e3fvC0Rk5xcXs9Ie7J1ylA=
  on:
    tags: true
  edge: true
